// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *StartSearchRequest) setDefaults() {
	{
		val := int(100)
		s.MessageSize.SetTo(val)
	}
	{
		val := int(10)
		s.MessageCount.SetTo(val)
	}
}
