// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleS2STokenAuth handles S2STokenAuth security.
	HandleS2STokenAuth(ctx context.Context, operationName OperationName, t S2STokenAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesS2STokenAuth = map[string][]string{
	StartSearchOperation: []string{},
}

func (s *Server) securityS2STokenAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t S2STokenAuth
	const parameterName = "X-Server-Side-Token"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesS2STokenAuth[operationName]
	rctx, err := s.sec.HandleS2STokenAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// S2STokenAuth provides S2STokenAuth security value.
	S2STokenAuth(ctx context.Context, operationName OperationName) (S2STokenAuth, error)
}

func (s *Client) securityS2STokenAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.S2STokenAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"S2STokenAuth\"")
	}
	req.Header.Set("X-Server-Side-Token", t.APIKey)
	return nil
}
