// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// StartSearch implements startSearch operation.
//
// Initiate a search for specified token.
//
// POST /api/v1/search
func (UnimplementedHandler) StartSearch(ctx context.Context, req *StartSearchRequest, params StartSearchParams) (r StartSearchRes, _ error) {
	return r, ht.ErrNotImplemented
}
