// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/Error
type Error struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type S2STokenAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *S2STokenAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *S2STokenAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *S2STokenAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *S2STokenAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/SearchMessage
type SearchMessage struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *SearchMessage) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *SearchMessage) SetMessage(val string) {
	s.Message = val
}

type StartSearchBadRequest Error

func (*StartSearchBadRequest) startSearchRes() {}

type StartSearchForbidden Error

func (*StartSearchForbidden) startSearchRes() {}

type StartSearchInternalServerError Error

func (*StartSearchInternalServerError) startSearchRes() {}

type StartSearchOKApplicationJSON []SearchMessage

func (*StartSearchOKApplicationJSON) startSearchRes() {}

// Ref: #/components/schemas/StartSearchRequest
type StartSearchRequest struct {
	Site         string `json:"site"`
	MessageSize  OptInt `json:"message_size"`
	MessageCount OptInt `json:"message_count"`
}

// GetSite returns the value of Site.
func (s *StartSearchRequest) GetSite() string {
	return s.Site
}

// GetMessageSize returns the value of MessageSize.
func (s *StartSearchRequest) GetMessageSize() OptInt {
	return s.MessageSize
}

// GetMessageCount returns the value of MessageCount.
func (s *StartSearchRequest) GetMessageCount() OptInt {
	return s.MessageCount
}

// SetSite sets the value of Site.
func (s *StartSearchRequest) SetSite(val string) {
	s.Site = val
}

// SetMessageSize sets the value of MessageSize.
func (s *StartSearchRequest) SetMessageSize(val OptInt) {
	s.MessageSize = val
}

// SetMessageCount sets the value of MessageCount.
func (s *StartSearchRequest) SetMessageCount(val OptInt) {
	s.MessageCount = val
}
