app:
  http:
    port: "8008"
  logger:
    loglvl: debug
    mode: development
    encoding: json
  s2s:
    header: X-Server-Side-Token
    clients:
      - name: vixarapi
        token: devVixarApiToken
